### ISSUE TITLE
How to mark a transaction as failed

### ISSUE THREAD

**Issue by marty-macfly** [pinpoint-apm/pinpoint-php-aop#21]
When the web server is having an issue like 500 error the transaction is mark as `success` in the web interface of pinpoint.

![2021-07-20 12 28 42 127 0 0 1 a9557ff2d023](https://user-images.githubusercontent.com/12715929/126266703-0dd2e615-59dc-46d2-a82a-45f9d4e3f211.png)

Return code is 500 but not consider as an error

![2021-07-20 12 30 18 127 0 0 1 8ab4e442e63d](https://user-images.githubusercontent.com/12715929/126266801-c688250e-34c1-4ba5-b7b3-7df59a512ea8.png)

What need to be done in the plugin to make it mark as `failed` ? Or if it's not possible what is a `failed` transaction ?

**Comment by marty-macfly** [comment]
I've found this issue https://github.com/pinpoint-apm/pinpoint-c-agent/issues/63 which is abou the same question but I didn't find which API has been added to support that or if it has been added yet @eeliu  ?

**Comment by eeliu** [comment]
@marty-macfly 
We did not add `mark_error` as python agent.

![image](https://user-images.githubusercontent.com/27064129/126585413-a3607315-42d0-42a5-b1d2-d2c7b5ae7f05.png)


https://github.com/pinpoint-apm/pinpoint-c-agent/blob/314b46e5e2bf7676cfdde7b3bf02651154b947a7/src/PY/help(pinpointPy).txt#L34-L35

In php-agent, transactions was marked as error when catch fetal error.

While, I will add this feature for you. 

Please watch the process on pinpoint-c-agent !

**Comment by eeliu** [comment]
@marty-macfly 

Please fellow https://github.com/eeliu/pinpoint-c-agent/tree/feat-php-error

https://github.com/eeliu/pinpoint-c-agent/blob/59c80a8705c948fb9af8488897f972ef218ddc74/src/PHP/pinpoint_php_api.php#L65-L72

If you found some problems, use current issue.

Please close this issue when test is done!

**Comment by marty-macfly** [comment]
It's working properly, can you merge it into https://github.com/pinpoint-apm/pinpoint-c-agent ?

**Comment by marty-macfly** [comment]
Seen the merge thanks https://github.com/pinpoint-apm/pinpoint-c-agent/pull/349
