### ISSUE TITLE
Error when use PDO and mysqli under php8

### ISSUE THREAD

**Issue by EyelynSu** [pinpoint-apm/pinpoint-php-aop#36]
[env]
PHP 8.1.0 (cli)

[result]
> PDO

        think\exception\ErrorException: Declaration of Pinpoint\Plugins\Sys\PDO\ProfilerPDOStatement::fetchAll(int $mode = PDO::FETCH_DEFAULT, Pinpoint\Plugins\Sys\PDO\mixed ...$args) should be compatible with PDOStatement::fetchAll($how = NULL, $class_name = NULL, $ctor_args = NULL) in vendor/pinpoint-apm/pinpoint-php-aop/lib/Pinpoint/Plugins/Sys/PDO/ProfilerPDOStatement.php:101

> mysqli

![1641808448](https://user-images.githubusercontent.com/41946743/149079196-03f567a3-c7a4-4e83-972c-dc502bf4e0b4.png)

**Comment by eeliu** [comment]
Got it! 

PHP8 changed a lot ！
