### ISSUE TITLE
Error when use Kafka under php8

### ISSUE THREAD

**Issue by mayingping-Bella** [pinpoint-apm/pinpoint-php-aop#40]
**Env:** 

- php 8.1.0
- kafka 6.0.0(latest)

**When send requests, there is an error:**
Deprecated: Return type of Pinpoint\Plugins\Sys\RdKafka\Producer::addBrokers($blocker_list) should either be compatible with RdKafka::addBrokers(string $broker_list): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~/pinpoint-c-agent/testapps/PHP/vendor/pinpoint-apm/pinpoint-php-aop/lib/Pinpoint/Plugins/Sys/RdKafka/Producer.php on line 13

Deprecated: Return type of Pinpoint\Plugins\Sys\RdKafka\Producer::newTopic($topic, $topic_conf = null) should either be compatible with RdKafka::newTopic(string $topic_name, ?RdKafka\TopicConf $topic_conf = null): RdKafka\Topic, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~/pinpoint-c-agent/testapps/PHP/vendor/pinpoint-apm/pinpoint-php-aop/lib/Pinpoint/Plugins/Sys/RdKafka/Producer.php on line 19
string(13) "test-pinpoint"

**Comment by eeliu** [comment]
It looks php8 not fully support !

#38 #36 , the same problem
